<div style="display: flex; flex-direction: row; justify-content: space-between; font-weight: bold; text-decoration: none">
<a href="02_exploratory_data_analysis.ipynb"><<< Back to Exploratory Data Analysis</a>
<a href="../README.md"> Go to README File (Conclusions) >>> </a>
</div>

In [2]:
import duckdb 
import pandas as pd

## Electric Vehicle Insights and Visualizations

### Introduction of Analysis and Business Context

### Objectives / Questions

These are the same questions from the previous section, but I decided to group them by common topic so they can be answered with similar queries. 

**Brand and Model Dominance**
1) What are the top EV brands across the United States?
2) Which models and model years are the most popular and least popular of EV brands?
3) What are the top ten most popular makes of cars? Of those ten, what are the distribution of models by make?
    
    **Segmented by Electric Vehicle Type**
    1) What are the top five most popular cars by Electric Vehicle Type?
    2) What is the distribution of Electric Vehicle Type cars by year? 
    3) What are the most popular and least popular brands and models in each county?

**Geographic Relevance**
1) Which counties and cities have the most EVs?
2) Which states and counties have the highest concentration of top EV brands?

    **Segmented by Electric Vehicle Type**
    1) Which are the top five counties or cities in terms of each type Electric Vehicle type?
    2) Which counties and of those counties, which cities have the most electric cars split by Electric Vehicle type?
    3) How many cars are in each city by Electric Vehicle Type?

**Range and Capability**

1) Which brands and models have the highest Electric Range and the lowest?
2) What are the max and min Electric ranges of both Electric Vehicle types?

**Historical Adoption Trends**

1) How has the number of Battery Electric and Plug-In Hybrid changed over the years?

### Loading Cleaned Data

In [3]:
df = pd.read_csv("../data/cleaned/data_wo_fuel.csv")
df

,County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligible?,Electric Range (in Miles),Vehicle Location,Electric Utility
0,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric (BEV),True,73.0,POINT (-117.90454 48.54657),AVISTA CORP
1,Yakima,Yakima,WA,98903.0,2023,SUBARU,SOLTERRA,Battery Electric (BEV),NaN,NaN,POINT (-120.71847 46.55029),PACIFICORP
2,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric (BEV),True,151.0,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
3,Kitsap,Poulsbo,WA,98370.0,2025,BMW,X5,Plug-in Hybrid (PHEV),True,40.0,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC
4,Thurston,Yelm,WA,98597.0,2015,FIAT,500,Battery Electric (BEV),True,87.0,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC
...,...,...,...,...,...,...,...,...,...,...,...,...
279775,Clark,Washougal,WA,98671.0,2024,HONDA,PROLOGUE,Battery Electric (BEV),NaN,NaN,POINT (-122.35341 45.57923),BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF C...
279776,King,Seattle,WA,98103.0,2019,BMW,I3,Plug-in Hybrid (PHEV),True,126.0,POINT (-122.35436 47.67596),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)
279777,King,Sammamish,WA,98075.0,2026,RIVIAN,R1S,Battery Electric (BEV),NaN,NaN,POINT (-122.03539 47.61344),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
279778,Pierce,Bonney Lake,WA,98391.0,2026,TESLA,MODEL Y,Battery Electric (BEV),NaN,NaN,POINT (-122.17144 47.19175),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)
279779,Pierce,Graham,WA,98338.0,2024,CHEVROLET,BLAZER,Battery Electric (BEV),NaN,NaN,POINT (-122.29477 47.05703),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)

In [16]:
results = duckdb.sql("""
                     SELECT * FROM df
                     WHERE Make = 'NISSAN' AND "Electric Vehicle Type" = 'Battery Electric (BEV)'
                     """).df()
results

,County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligible?,Electric Range (in Miles),Vehicle Location,Electric Utility,WA Retail Gas Prices (Dollars per Gallon)
0,Stevens,Colville,WA,99114.0,2012,NISSAN,LEAF,Battery Electric (BEV),True,73.0,POINT (-117.90454 48.54657),AVISTA CORP,3.883
1,King,Seattle,WA,98122.0,2018,NISSAN,LEAF,Battery Electric (BEV),True,151.0,POINT (-122.31009 47.60803),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),3.269
2,Thurston,Olympia,WA,98502.0,2015,NISSAN,LEAF,Battery Electric (BEV),True,84.0,POINT (-122.92333 47.03779),PUGET SOUND ENERGY INC,2.754
3,Kitsap,Poulsbo,WA,98370.0,2016,NISSAN,LEAF,Battery Electric (BEV),True,84.0,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,2.531
4,King,Seattle,WA,98133.0,2018,NISSAN,LEAF,Battery Electric (BEV),True,151.0,POINT (-122.33364 47.73709),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),3.269
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16159,King,Kent,WA,98042.0,2023,NISSAN,ARIYA HATCHBACK,Battery Electric (BEV),<NA>,NaN,POINT (-122.10798 47.37124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),4.541
16160,Clark,Washougal,WA,98671.0,2019,NISSAN,LEAF,Battery Electric (BEV),True,150.0,POINT (-122.35341 45.57923),BONNEVILLE POWER ADMINISTRATION||PACIFICORP||P...,3.186
16161,King,Bellevue,WA,98008.0,2022,NISSAN,LEAF,Battery Electric (BEV),<NA>,NaN,POINT (-122.11867 47.63131),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),4.659
16162,King,Maple Valley,WA,98038.0,2023,NISSAN,LEAF,Battery Electric (BEV),<NA>,NaN,POINT (-122.04526 47.39394),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),4.541
16163,Whatcom,Bellingham,WA,98225.0,2023,NISSAN,ARIYA HATCHBACK,Battery Electric (BEV),<NA>,NaN,POINT (-122.47091 48.75256),PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM CO...,4.541

### Answering Questions: Querying and Visual Analysis

#### Brand Dominance Questions

1) What are the top EV brands across the United States?

2) Which models and model year are the most popular and least popular of EV brands?

3) What are the top ten most popular makes of cars? Of those ten, what are the distribution of models by make?

##### Segmentation Questions by Electric Vehicle Type

1) What are the top five most popular cars by Electric Vehicle Type?

2) What is the distribution of Electric Vehicle Type cars by year?

3) What are the most popular and least popular brands and models in each county?

#### Geographic Relevance Questions

1) Which counties and cities have the most EVs?

2) Which states and counties have the highest concentration of top EV brands?

##### Segmentation Questions by Electric Vehicle Type

1) Which are the top five counties or cities in terms of each type Electric Vehicle type?

2) Which counties and of those counties, which cities have the most electric cars split by Electric Vehicle type?

3) How many cars are in each city by Electric Vehicle Type?

#### Range and Capability Questions

1) Which brands and models have the highest Electric Range and the lowest?

2) What are the max and min Electric ranges of both Electric Vehicle types?

#### Historical Adoption Trends Questions

1) How has the number of Battery Electric and Plug-In Hybrid changed over the years?

## Key Insights

## Conclusions and Next Steps

<div style="display: flex; flex-direction: row; justify-content: space-between; font-weight: bold; text-decoration: none">
<a href="02_exploratory_data_analysis.ipynb"><<< Back to Exploratory Data Analysis</a>
<a href="../README.md"> Go to README File (Conclusions) >>> </a>
</div>